---
version: "3.3"
services:
  bot_app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres:db

  postgres:
    image: "postgres:12"
    restart: "always"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgres/data
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./scripts/pg_hba_dev.conf:/etc/postgresql/pg_hba.conf
    command: |
      postgres
      -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  postgres_data:
    driver: local